# Exported from Render on 2024-07-12T18:32:51Z
services:
- type: web
  name: noteit-prod
  runtime: node
  repo: https://github.com/kaushikappani/noteit
  plan: free
  envVars:
  - fromGroup: noteit-prod-2
  region: singapore
  # buildCommand: rm -rf node_modules package-lock.json && npm i
  buildCommand : npm install
  startCommand: npm start
  healthCheckPath: /health
version: "1"